controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    position_controller:
      type: position_controllers/JointGroupPositionController
    
    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

velocity_controllers:
  ros__parameters:
    joints: 
      - left_joint_f
      - right_joint_f
      - left_joint_b
      - right_joint_b
    command_interface: 
      - velocity
    state_interface: 
      - velocity
      - effort

position_controller:
  ros__parameters:
    joints:
      - left_joint_s
      - right_joint_s
    command_interface: 
      - position
    state_interface: 
      - velocity
      - effort


forward_position_controller:
  ros__parameters:
    joints:
      - left_joint_s
      - right_joint_s
      - left_joint_f
      - right_joint_f
      - left_joint_b
      - right_joint_b
    interface_name: position


joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - left_joint_s
      - right_joint_s

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
